apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f kafka-rest.yml -c
    kompose.version: 1.31.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ksqldb-server
  name: ksqldb-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksqldb-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f kafka-rest.yml -c
        kompose.version: 1.31.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka-compose-default: "true"
        io.kompose.service: ksqldb-server
    spec:
      containers:
        - env:
            - name: KSQL_BOOTSTRAP_SERVERS
              value: broker:29092
            - name: KSQL_CACHE_MAX_BYTES_BUFFERING
              value: "0"
            - name: KSQL_CONFIG_DIR
              value: /etc/ksql
            - name: KSQL_HOST_NAME
              value: ksqldb-server
            - name: KSQL_KSQL_CONNECT_URL
              value: http://connect:8083
            - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
              value: "true"
            - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
              value: "true"
            - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
            - name: KSQL_LISTENERS
              value: http://0.0.0.0:8088
          image: confluentinc/cp-ksqldb-server:7.5.0
          name: ksqldb-server
          ports:
            - containerPort: 8088
              hostPort: 8088
              protocol: TCP
          resources: {}
      hostname: ksqldb-server
      restartPolicy: Always
status: {}
