apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f kafka-rest.yml -c
    kompose.version: 1.31.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rest-proxy
  name: rest-proxy
  namespace: default
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: rest-proxy
status:
  loadBalancer: {}
