apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f kafka-rest.yml
    kompose.version: 1.31.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rest-proxy
  name: rest-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rest-proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f kafka-rest.yml
        kompose.version: 1.31.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka-compose-default: "true"
        io.kompose.service: rest-proxy
    spec:
      containers:
        - env:
            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              value: broker:29092
            - name: KAFKA_REST_HOST_NAME
              value: rest-proxy
            - name: KAFKA_REST_LISTENERS
              value: http://0.0.0.0:8082
            - name: KAFKA_REST_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
          image: confluentinc/cp-kafka-rest:7.5.0
          name: rest-proxy
          ports:
            - containerPort: 8082
              hostPort: 8082
              protocol: TCP
          resources: {}
      hostname: rest-proxy
      restartPolicy: Always
status: {}
